### ISSUE TITLE
(possible) memory issue in censo

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/lodown#100] opened 2017-05-30 16:39 UTC
While running

```
memory.limit(128000)

library(lodown)

outdir <- normalizePath("~/Censo")

unlink( outdir , recursive = TRUE )

catalog <- get_catalog( "censo" , output_dir = outdir )
catalog <- catalog[ catalog$year == 2010 , ]

# catalog <- catalog[ catalog$year == 2010 , ]
# catalog <- catalog[ grepl( "^mg", catalog$db_table_prefix) , ]

lodown( "censo" , catalog = catalog )
```
issues

```
Error in .local(conn, statement, ...) : 
  Unable to execute statement 'create table c10_pes_pre_fpc as (SELECT * FROM ac10_pes) UNION ALL (SELECT * FROM al10_pes) UNION AL...'.
 !ERROR: HEAPextend: failed to extend to 443641 for 04\56\45655.tail: h->storage == STORE_MEM && can_map && fd >= 0 && HEAPload_intern() != GDK_SUCCEED '.
Called from: .local(conn, statement, ...)
```

**Comment by ajdamico** [comment] 2017-05-31 12:37
i can't reproduce this :(

	setwd("S:/temp/CENSO")
	devtools::install_github("hannesmuehleisen/MonetDBLite")
	devtools::install_github("ajdamico/lodown")
	library(lodown)
	lodown("censo")

**Comment by guilhermejacob** [comment] 2017-06-06 13:20
When running this:
```
library(lodown)

memory.limit(128000)
output_dir <- normalizePath( "D:/Censo" )
unlink( output_dir , recursive = TRUE )

catalog <- get_catalog( "censo" , output_dir = output_dir )
catalog <- subset( catalog , year == 2010 )

lodown( "censo" , catalog = catalog )
```

This error ocurred:
```
"Unable to execute statement 'create table c10 as (SELECT a.* , b.v0502, b.v0504, b.v0601, b.v6033, b.v6036, b.v6037, b.v6040, b.v...'.\nServer says 'MALException:algebra.join:Object not found !ERROR: MT_mmap: CreateFileMapping(000000000001F6F4, &sa, 4, 60, 3197304832, NULL) failed !OS: The printer is out of paper.\r !ERROR: HEAPextend: failed to extend to 260895342592 for 05\\50\\55076.tail: GDKmremap() failed !ERROR: MT_munmap failed !OS: The device does not recognize the command.\r !ERROR: HEAPfree: 05\\50\\55076.tail was not mapped !OS: The operation completed successfully.\r '."
```

Info:
```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252
[3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C
[5] LC_TIME=Portuguese_Brazil.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] lodown_0.1.0

loaded via a namespace (and not attached):
 [1] compiler_3.4.0    Matrix_1.2-9      survey_3.31-5     DBI_0.6-1
 [5] survival_2.41-3   RCurl_1.95-4.8    SAScii_1.0        MonetDBLite_0.3.3
 [9] splines_3.4.0     codetools_0.2-15  grid_3.4.0        digest_0.6.12
[13] bitops_1.0-6      lattice_0.20-35
```

**Comment by ajdamico** [comment] 2017-06-06 13:23
@hannesmuehleisen any obvious culprits here?

**Comment by hannesmuehleisen** [comment] 2017-06-06 14:30
Disk full?

**Comment by hannesmuehleisen** [comment] 2017-06-06 14:32
Funky folder names?

**Comment by hannesmuehleisen** [comment] 2017-06-06 14:38
This should obviously not happen.

**Comment by ajdamico** [comment] 2017-06-07 02:09
hi, ascii folder name.  i am pretty convinced this is a memory issue.  exact same code works fine on more powerful unix and windows machines (tested again tonight).  likely duplicate of the easier to reproduce ram issues listed at https://github.com/hannesmuehleisen/MonetDBLite/issues  thanks

**Comment by ajdamico** [comment] 2017-06-13 14:09
rocks109 (with 16gb of ram) gives a different (but also unexpected) error.  there's no way that censo requires the 256gb of ram designated by the `memory.limit(256000)` call at the start of this script



	R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
	Copyright (C) 2017 The R Foundation for Statistical Computing
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.


	This is a session spawned by NppToR.


	> memory.limit(256000)
	[1] 256000
	> lodown::lodown("censo",output_dir="C:/My Directory/CENSO")
	building catalog for censo


	locally downloading censo


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/AC.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/8d33c41dcfde91034b1afbc3105bd061.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 1 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/AL.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/675d0405924a1b73a6f889f953a759ab.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 2 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/AM.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/8a1e7a9111551585f7cec0b7b767e0c7.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 3 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/AP.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/6eeff2ce0144bb14d5a56c6ca27fcdf9.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 4 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/BA.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/f12488e852651d05e153bb9f21b670ed.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 5 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/CE.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/6e5d97ea080321a3f736da278ccb0c36.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 6 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/DF.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/31c64b57fe5442cb7c07b351e8c5a51c.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 7 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/ES.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/b751b8a9e5ee7aa58c52b86c25bd041e.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 8 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/GO.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/f29a3850a4b737df7e2e8ea62f0007b9.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 9 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/MA.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/362a6e810463c8a0e38517f5163cc222.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 10 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/MG.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/90c71c4f917ad6d89d0f453c2e3c2dc9.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 11 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/MS.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/b5e5b1b9e2e979e74c9ec72feec10865.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 12 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/MT.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/86f0b09d2b55f9efa586af32e4f2314a.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 13 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/PA.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/738b3f4e5c93d2280a8b0a744134c648.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 14 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/PB.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/8bd47199975bdf2964c09aa4e21648e1.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 15 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/PE.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/eac1739962da73a00dfb693f03377c92.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 16 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/PI.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/06c1460710d6b2b70933afe955bf06ee.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 17 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/PR.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/409a9525b7a91b4618baf65cc89dce07.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 18 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/RJ.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/5b82d082ec19bfb478942334dee06362.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 19 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/RN.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/791786e4d34a82d9602a9782cfcf56ee.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 20 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/RO.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/d1e8db0e4c49bf7785e6765a73a0ef97.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 21 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/RR.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/30da4639719883b3e680399fe5f3f7c5.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 22 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/RS.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/989abcab6ef8f4cc0482c4da694d254e.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 23 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/SC.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/5aa8eea1b7368218b7503d61f196b586.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 24 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/SE.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/af4222637a1c8e705f816d7a78284a2f.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 25 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/SP1.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/5493bb945da3b02e07808de8b2c38054.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 26 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/SP2_RM.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/688c1a930ab09e425507f8e308e0d3cc.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 27 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_Gerais_da_Amostra/Microdados/TO.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/319c75b43a1d30166e3a0185c3a7d1ad.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 28 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/AC.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/3158420f453db3abf89b2d647c545c9e.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 29 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/AL.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/3473aaca4434223eac3634e7eac9965d.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 30 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/AM.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/b657c933458434270a7dada54c82c8c2.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 31 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/AP.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/712d828d55c1b711c360f31fd352bd51.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 32 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/BA.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/ac71b32d6cb285e878395ffccfc37827.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 33 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/CE.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/a66f04aa4f01d0bbac0f765885b853b8.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 34 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/DF.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/42dbf65e1e461590c8abd89556ba9d7f.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 35 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/ES.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/8a6e1bfb9b9c58f723962bcdb62d4585.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 36 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/GO.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/dea5ae30bababc5364b4be4c0b37bd31.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 37 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/MA.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/d9330acd395aee9d95ac6e3fb9229afb.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 38 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/MG.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/2d4fbdaced04e2b5ab8458e5547311d4.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 39 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/MS.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/00fe0dc0835f77b0c6f494027b5bc115.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 40 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/MT.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/872d388baa776ea816785e3bf51da1d5.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 41 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/PA.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/46f2d62d5acb450a90e55303e15d6566.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 42 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/PB.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/6adeece64f7bb1d6c17d341ecd719174.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 43 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/PE.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/56fe3493a6712192de4c49d4144bb9cd.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 44 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/PI.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/fa48f71d99a2e87e535a33b11998f196.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 45 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/PR.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/1474fc80edc712378a38e4703fb7ba15.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 46 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/RJ.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/e2796c8aefb01e37e3f0bc8ec0ff393d.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 47 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/RN.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/b0a4513a2579a80f22c46ebd7e4e8844.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 48 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/RO.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/6e5fdbd3a62745e6de914d64079090d8.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 49 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/RR.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/edb2801a04e82b96f0371284d15d599d.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 50 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/RS.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/6dcd05a6e229667e22d6be66805c32e7.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 51 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/SC.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/d0702f127aa2f8d39720ea4b1adf59a4.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 52 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/SE.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/da244d977ae2392fec9c6c4a17a20c80.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 53 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/SP.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/b0e866236505e3efa2def09f2bdb7207.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 54 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	'ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Microdados/TO.zip'

	cached in

	'C:/Users/damico/AppData/Local/Temp/ad017a730b2e7d31eace694a2fe0fd08.Rcache'

	copying to

	'C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c1d7b1ca6'


	censo catalog entry 55 of 55 stored in 'C:/My Directory/CENSO/MonetDB'


	censo survey design entry 1 of 5 stored at 'C:/My Directory/CENSO/dom 2010 design.rds'


	censo survey design entry 2 of 5 stored at 'C:/My Directory/CENSO/dom 2000 design.rds'


	censo survey design entry 3 of 5 stored at 'C:/My Directory/CENSO/fam 2000 design.rds'


	censo survey design entry 4 of 5 stored at 'C:/My Directory/CENSO/pes 2010 design.rds'





	lodown is now exiting due to a memory error.
	your computing performance would suffer due to disk paging,
	but you can increase your memory limits with beyond your available hardware with the `?memory.limit` function.
	for example, you can set the memory ceiling of an R session to 128 GB by typing `memory.limit(128000)`.



	Error: cannot allocate vector of size 12.1 Gb
	In addition: Warning messages:
	1: In j :
	  closing unused connection 4 (C:\Users\damico\AppData\Local\Temp\RtmpSq88uC\file165c4621993)
	2: In j :
	  closing unused connection 3 (C:/Users/damico/Documents/R/win-library/3.4/lodown/extdata/censo/SASinputDom.txt)
	3: In .Internal(gc(verbose, reset)) :
	  closing unused connection 3 (C:/Users/damico/Documents/R/win-library/3.4/lodown/extdata/censo/LE_PESSOAS.sas)
	> sessionInfo()
	R version 3.4.0 (2017-04-21)
	Platform: x86_64-w64-mingw32/x64 (64-bit)
	Running under: Windows 10 x64 (build 15063)

	Matrix products: default

	locale:
	[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
	[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
	[5] LC_TIME=English_United States.1252    

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base     

	loaded via a namespace (and not attached):
	 [1] lattice_0.20-35   codetools_0.2-15  digest_0.6.12     bitops_1.0-6      grid_3.4.0        DBI_0.6-1        
	 [7] magrittr_1.5      survey_3.32       stringi_1.1.5     MonetDBLite_0.3.2 SAScii_1.0        Matrix_1.2-9     
	[13] splines_3.4.0     tools_3.4.0       lodown_0.1.0      stringr_1.2.0     RCurl_1.95-4.8    survival_2.41-3  
	[19] compiler_3.4.0   
	> memory.limit()
	[1] 256000
	> memory.size()
	[1] 30588.95
	>

**Comment by ajdamico** [comment] 2017-06-18 21:29
ran this for five days on a windows machine with 16gb and it never finished or errored out

**Comment by hannesmuehleisen** [comment] 2017-10-17 09:16
This should be fixed?

**Comment by ajdamico** [comment] 2017-10-17 11:42
@guilhermejacob please reopen in monetdblite if it's not fixed in dev, thanks

**Closed by ajdamico** 2017-10-17 11:42 UTC
