### ISSUE TITLE
Handle missing values

### ISSUE THREAD

**Issue by javiertury** [ajdamico/lodown#137] opened 2018-05-30 12:05 UTC
I'm running `scf_MIcombine()` for the scf2013 dataset. For this dataset, the values 0 or below are codes indicating missing values, inappropiate responses, etc. I replaced most of them by NAs in order not to bias the calculations. I use 'svrepdesign()' to construct an imputed replicated weighted survey design, but some observations have missing variables across all implicates. The following error occurs after running `scf_MIcombine()` with `svyglm()`.

```
Error in svrVar(betas, scale, rscales, mse = design$mse, coef = beta0) :
  All replicates contained NAs                            
```

To avoid the error, one can do these steps. First, build a list of variables that you are going to use in `svyglm()`. Sencond, remove all the observations that have missing at least one those variables across all implicates. Third, remove the weights of those observations. Fourth, build the survey design object using these filtered objects and run `scf_MIcombine()` with `svyglm()` .

However this becomes cumbersome as I often change the regression equation. Other functions, like `lm()` automatically handle NAs.

**Comment by ajdamico** [comment] 2018-05-30 12:10
need a minimal reproducible example

**Comment by ajdamico** [comment] 2018-05-31 19:21
duplicate of https://github.com/ajdamico/lodown/issues/139

**Closed by ajdamico** 2018-05-31 19:21 UTC

**Comment by javiertury** [comment] 2018-05-31 19:33
After investigating more I've pinpointed several issues. Most of them were because I was doing an incorrect treatment of data. The only issue that I can attribute to MIcombine is described in #139. I have yet to find identify the cause of few issues more.

I will describe how I was using data incorrectly. I had replaced all zeros and most of the negative values as NAs, so some survey functions raised warnings and errors. I've learned that you have to pass the `na.rm=T` arguments like for regular base r functions. Also, is critical to check that replicate weights(and maybe also regular weights) must not contain NAs.

PD: I apologize, every time I open an issue I'm very vague. I am not new to github and I should have learned this by now.
